FROM public.ecr.aws/docker/library/python:3.12-slim

WORKDIR /app

COPY ./requirements.txt /app/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /app/requirements.txt

COPY ./api /app/api
COPY ./model /app/model

# 确保 model 目录存在并有正确的权限
RUN mkdir -p /app/model && chmod 755 /app/model

ENV PORT=80

CMD ["sh", "-c", "uvicorn api.app:app --host 0.0.0.0 --port ${PORT}"]
